// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _123Vendas.Vendas.Infra.Data;

#nullable disable

namespace _123Vendas.Vendas.Infra.Migrations
{
    [DbContext(typeof(ComprasContext))]
    [Migration("20241111163608_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("_123Vendas.Vendas.Domain.Vendas.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompraStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCompra")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("_123Vendas.Vendas.Domain.Vendas.CompraItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.ToTable("CompraItens", (string)null);
                });

            modelBuilder.Entity("_123Vendas.Vendas.Domain.Vendas.CompraItem", b =>
                {
                    b.HasOne("_123Vendas.Vendas.Domain.Vendas.Compra", "Compra")
                        .WithMany("CompraItens")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("_123Vendas.Vendas.Domain.Vendas.Compra", b =>
                {
                    b.Navigation("CompraItens");
                });
#pragma warning restore 612, 618
        }
    }
}
